import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SWRProvider, JotaiProvider } from "@/components/providers";
import ErrorBoundary from "@/components/monitoring/ErrorBoundary";
import { WebVitalsMonitor } from "@/components/monitoring/PerformanceMonitor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project Scaffolder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorBoundary>
          <WebVitalsMonitor />
          <JotaiProvider>
            <SWRProvider>
              {children}
            </SWRProvider>
          </JotaiProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
